CREATE USER 'sti'@'localhost' IDENTIFIED BY  '***';

GRANT USAGE ON * . * TO  'sti'@'localhost' IDENTIFIED BY  '***' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
GRANT SELECT , INSERT , UPDATE , DELETE ON  `sti-mail` . * TO  'sti'@'localhost';